const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');

async function buildTicketArtifacts({ ticketId, bookingId, userId, eventId, quantity, amount }) {
  const qrPayload = JSON.stringify({
    ticketId,
    bookingId,
    userId,
    eventId,
    quantity,
    issuedAt: new Date().toISOString(),
  });
  const qrPngBuffer = await QRCode.toBuffer(qrPayload, { errorCorrectionLevel: 'M', width: 240 });

  const pdfBuffer = await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A5', margin: 40 });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(22).text('Event Ticket', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#666')
       .text('Generated by Payment & Ticketing Service', { align: 'center' });
    doc.moveDown(1);
    doc.fillColor('#000').fontSize(12);
    doc.text(`Ticket ID: ${ticketId}`);
    doc.text(`Booking:   ${bookingId}`);
    doc.text(`Event:     ${eventId}`);
    doc.text(`Holder:    ${userId}`);
    doc.text(`Quantity:  ${quantity}`);
    doc.text(`Amount:    ${amount.toFixed(2)}`);
    doc.moveDown(1);
    doc.image(qrPngBuffer, { fit: [200, 200], align: 'center' });
    doc.moveDown(8);
    doc.fontSize(8).fillColor('#888')
       .text('Present this QR at the entrance. Issued via CQRS + Event Sourcing.', { align: 'center' });
    doc.end();
  });

  return { qrPayload, pdfBuffer };
}

module.exports = { buildTicketArtifacts };
